# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'atsource' do
  pod 'AppCenter/Crashes', '~> 2.5.0'
  pod 'AppCenter/Analytics', '~> 2.5.0'
  pod 'AppCenterReactNativeShared', '~> 2.5.0'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for atsource

  

  platform :ios, '9.0'
  target 'atsourceTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'atsource-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for atsource-tvOS

  target 'atsource-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
